-- ============================================================
-- stg_customers
-- Source  : core.dim_customer  (built by Python ELT)
-- Purpose : Thin staging wrapper — select & rename columns.
--           Downstream marts decide any filtering (is_active etc.)
-- ============================================================

with source as (

    select * from {{ source('core', 'dim_customer') }}

),

renamed as (

    select
        -- surrogate key (generated by ELT SERIAL)
        customer_key,

        -- natural key from ERP
        customer_id,
        customer_code,

        -- identity
        prefix_client,
        company,
        company_short,
        representative,
        coalesce(
            representative,
            company,
            customer_code   -- fallback: nếu cả hai NULL thì dùng mã khách
        ) as fullname,   -- fullname NULL in ERP; derive from representative → company → code
        phonenumber,
        email,

        -- classification
        type_client,
        vip_rating,
        status_clients,
        is_active,

        -- geography
        country,
        city,
        district,
        ward,
        address,

        -- financials
        vat,
        debt_limit,
        debt_limit_day,
        discount,
        table_price_id,
        time_payment,

        -- price group (denormalised from dim_price_group via setup.py)
        price_group_key,
        price_group_code,
        price_group_name,

        -- metadata
        datecreated,
        etl_loaded_at

    from source

)

select * from renamed
